export default function Head(): JSX.Element {
  return (
    <>
      <title>Secretaria Virtual: Flor de Jagube</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
